extern const GeoLayout ow_dnvic_close[];
extern Lights1 ow_dnvic_close_f3d_material_005_lights;
extern Lights1 ow_dnvic_close_f3d_material_006_lights;
extern u8 ow_dnvic_close_tex1_64x64_ED3777AC0FAF94A2_13_ia8[];
extern u8 ow_dnvic_close_dnvic40s_ci8[];
extern u8 ow_dnvic_close_dnvic40s_ci8_pal_rgba16[];
extern Vtx ow_dnvic_close_Plane_002_mesh_layer_4_vtx_cull[8];
extern Vtx ow_dnvic_close_Plane_002_mesh_layer_4_vtx_0[35];
extern Gfx ow_dnvic_close_Plane_002_mesh_layer_4_tri_0[];
extern Vtx ow_dnvic_close_Plane_002_mesh_layer_4_vtx_1[4];
extern Gfx ow_dnvic_close_Plane_002_mesh_layer_4_tri_1[];
extern Gfx mat_ow_dnvic_close_f3d_material_005[];
extern Gfx mat_revert_ow_dnvic_close_f3d_material_005[];
extern Gfx mat_ow_dnvic_close_f3d_material_006[];
extern Gfx mat_revert_ow_dnvic_close_f3d_material_006[];
extern Gfx ow_dnvic_close_Plane_002_mesh_layer_4[];
extern Gfx ow_dnvic_close_material_revert_render_settings[];
