extern const GeoLayout hollowstar_geo[];
extern Lights1 hollowstar___f3d_lights;
extern u8 hollowstar___i8[];
extern Vtx hollowstar_hollowstar_mesh_layer_1_vtx_cull[8];
extern Vtx hollowstar_hollowstar_mesh_layer_1_vtx_0[30];
extern Gfx hollowstar_hollowstar_mesh_layer_1_tri_0[];
extern Gfx mat_hollowstar___f3d[];
extern Gfx mat_revert_hollowstar___f3d[];
extern Gfx hollowstar_hollowstar_mesh_layer_1[];
extern Gfx hollowstar_material_revert_render_settings[];
