#include "src/game/envfx_snow.h"

const GeoLayout ccm_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_a1_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 1196, 354, 5, 0, 173, 0, ccm_dl_a1_001_mesh_layer_1),
		GEO_CULL(-20000, 20000, -20000, 20000, 0, 20000),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_a2_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_a2_001_mesh_layer_1),
		GEO_CULL(-20000, 20000, -20000, 20000, 0, 20000),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_a3_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_a3_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_c4_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ccm_dl_c4_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, ccm_dl_c4_mesh_layer_2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_c4_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ccm_dl_c4_002_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_c4_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_c4_003_mesh_layer_1),
		GEO_CULL(-20000, 20000, -20000, 20000, 0, 20000),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_c4_004_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_c4_005_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ccm_dl_Plane_001_mesh_layer_3),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 10154, 3269, -5064, 90, 0, 0, ccm_dl_water_thing_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ccm_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -160, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ccm_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, ccm_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ccm_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ccm_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ccm_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
