extern const GeoLayout castle_courtyard_area_1_geo[];
extern const GeoLayout castle_courtyard_area_1[];
extern const Collision castle_courtyard_area_1_collision[];
extern const MacroObject castle_courtyard_area_1_macro_objs[];
extern Lights1 castle_courtyard_dl_f3d_material_lights;
extern Lights1 castle_courtyard_dl_f3d_material_002_layer1_area1_lights;
extern Lights1 castle_courtyard_dl__xd_layer1_area1_lights;
extern u8 castle_courtyard_dl__0E01BF00_ci4[];
extern u8 castle_courtyard_dl__0E01BF00_ci4_pal_rgba16[];
extern u8 castle_courtyard_dl_white_ia16[];
extern u8 castle_courtyard_dl_white_i8[];
extern Vtx castle_courtyard_dl___mesh_layer_4_vtx_cull[8];
extern Vtx castle_courtyard_dl___mesh_layer_4_vtx_0[4];
extern Gfx castle_courtyard_dl___mesh_layer_4_tri_0[];
extern Vtx castle_courtyard_dl_epi_001_mesh_layer_1_vtx_cull[8];
extern Vtx castle_courtyard_dl_epi_001_mesh_layer_1_vtx_0[1814];
extern Gfx castle_courtyard_dl_epi_001_mesh_layer_1_tri_0[];
extern Vtx castle_courtyard_dl_epi_001_mesh_layer_1_vtx_1[8];
extern Gfx castle_courtyard_dl_epi_001_mesh_layer_1_tri_1[];
extern Vtx castle_courtyard_dl_epi_001_mesh_layer_1_vtx_2[404];
extern Gfx castle_courtyard_dl_epi_001_mesh_layer_1_tri_2[];
extern Gfx mat_castle_courtyard_dl_f3d_material[];
extern Gfx mat_revert_castle_courtyard_dl_f3d_material[];
extern Gfx mat_castle_courtyard_dl_f3d_material_002_layer1_area1[];
extern Gfx mat_revert_castle_courtyard_dl_f3d_material_002_layer1_area1[];
extern Gfx mat_castle_courtyard_dl__xd_layer1_area1[];
extern Gfx mat_revert_castle_courtyard_dl__xd_layer1_area1[];
extern Gfx mat_castle_courtyard_dl_f3d_material_004_layer1[];
extern Gfx mat_revert_castle_courtyard_dl_f3d_material_004_layer1[];
extern Gfx castle_courtyard_dl___mesh_layer_4[];
extern Gfx castle_courtyard_dl_epi_001_mesh_layer_1[];
extern Gfx castle_courtyard_dl_material_revert_render_settings[];
