extern void scroll_castle_courtyard_dl_castle2_mesh_layer_4_vtx_0();
extern void scroll_castle_courtyard_dl_castle2_mesh_layer_5_vtx_0();
extern void scroll_castle_courtyard_dl_Circle_mesh_layer_5_vtx_0();
extern void scroll_castle_courtyard();
