extern const GeoLayout Dan_area_1_geo[];
extern const GeoLayout Dan_area_1[];
extern const Collision Dan_area_1_collision[];
extern const MacroObject Dan_area_1_macro_objs[];
extern u8 Dan_dl_NewFloor_ci4[];
extern u8 Dan_dl_NewFloor_ci4_pal_rgba16[];
extern u8 Dan_dl_Rock_DirtUpperG_i4[];
extern u8 Dan_dl_Rock_DirtUpperC_rgba16[];
extern u8 Dan_dl_leaves_rgba16[];
extern u8 Dan_dl_bb_rgba16[];
extern Vtx Dan_dl_model_mesh_layer_1_vtx_cull[8];
extern Vtx Dan_dl_model_mesh_layer_1_vtx_0[348];
extern Gfx Dan_dl_model_mesh_layer_1_tri_0[];
extern Vtx Dan_dl_model_mesh_layer_1_vtx_1[59];
extern Gfx Dan_dl_model_mesh_layer_1_tri_1[];
extern Vtx Dan_dl_model_mesh_layer_5_vtx_cull[8];
extern Vtx Dan_dl_model_mesh_layer_5_vtx_0[420];
extern Gfx Dan_dl_model_mesh_layer_5_tri_0[];
extern Vtx Dan_dl_model_mesh_layer_4_vtx_cull[8];
extern Vtx Dan_dl_model_mesh_layer_4_vtx_0[300];
extern Gfx Dan_dl_model_mesh_layer_4_tri_0[];
extern Gfx mat_Dan_dl_grass_f3d_layer1[];
extern Gfx mat_revert_Dan_dl_grass_f3d_layer1[];
extern Gfx mat_Dan_dl_rock_f3d_layer5[];
extern Gfx mat_revert_Dan_dl_rock_f3d_layer5[];
extern Gfx mat_Dan_dl_leaves_f3d[];
extern Gfx mat_revert_Dan_dl_leaves_f3d[];
extern Gfx mat_Dan_dl_bb_f3d[];
extern Gfx mat_revert_Dan_dl_bb_f3d[];
extern Gfx Dan_dl_model_mesh_layer_1[];
extern Gfx Dan_dl_model_mesh_layer_5[];
extern Gfx Dan_dl_model_mesh_layer_4[];
extern Gfx Dan_dl_material_revert_render_settings[];
