extern const GeoLayout vcutm_area_1_geo[];
extern const GeoLayout vcutm_area_1[];
extern const Collision vcutm_area_1_collision[];
extern const MacroObject vcutm_area_1_macro_objs[];
extern Lights1 vcutm_dl_Sumele_Hair_f3d_lights;
extern Lights1 vcutm_dl__auto_4_f3d_lights;
extern Lights1 vcutm_dl__1_f3d_lights;
extern Lights1 vcutm_dl__auto_5_f3d_lights;
extern Lights1 vcutm_dl__2_f3d_lights;
extern Lights1 vcutm_dl__3_f3d_lights;
extern u8 vcutm_dl__auto_4_i8[];
extern u8 vcutm_dl__1_ci4[];
extern u8 vcutm_dl__1_ci4_pal_rgba16[];
extern u8 vcutm_dl__auto_5_ci4[];
extern u8 vcutm_dl__auto_5_ci4_pal_rgba16[];
extern u8 vcutm_dl__2_ci4[];
extern u8 vcutm_dl__2_ci4_pal_rgba16[];
extern u8 vcutm_dl__3_ci4[];
extern u8 vcutm_dl__3_ci4_pal_rgba16[];
extern Vtx vcutm_dl_eye_001_mesh_layer_1_vtx_cull[8];
extern Vtx vcutm_dl_eye_001_mesh_layer_1_vtx_0[4];
extern Gfx vcutm_dl_eye_001_mesh_layer_1_tri_0[];
extern Vtx vcutm_dl_eye_002_mesh_layer_1_vtx_cull[8];
extern Vtx vcutm_dl_eye_002_mesh_layer_1_vtx_0[57];
extern Gfx vcutm_dl_eye_002_mesh_layer_1_tri_0[];
extern Vtx vcutm_dl_eye_002_mesh_layer_1_vtx_1[26];
extern Gfx vcutm_dl_eye_002_mesh_layer_1_tri_1[];
extern Vtx vcutm_dl_eye_002_mesh_layer_1_vtx_2[16];
extern Gfx vcutm_dl_eye_002_mesh_layer_1_tri_2[];
extern Vtx vcutm_dl_eye_002_mesh_layer_1_vtx_3[10];
extern Gfx vcutm_dl_eye_002_mesh_layer_1_tri_3[];
extern Vtx vcutm_dl_eye_002_mesh_layer_1_vtx_4[12];
extern Gfx vcutm_dl_eye_002_mesh_layer_1_tri_4[];
extern Gfx mat_vcutm_dl_Sumele_Hair_f3d[];
extern Gfx mat_vcutm_dl__auto_4_f3d[];
extern Gfx mat_revert_vcutm_dl__auto_4_f3d[];
extern Gfx mat_vcutm_dl__1_f3d[];
extern Gfx mat_revert_vcutm_dl__1_f3d[];
extern Gfx mat_vcutm_dl__auto_5_f3d[];
extern Gfx mat_revert_vcutm_dl__auto_5_f3d[];
extern Gfx mat_vcutm_dl__2_f3d[];
extern Gfx mat_revert_vcutm_dl__2_f3d[];
extern Gfx mat_vcutm_dl__3_f3d[];
extern Gfx mat_revert_vcutm_dl__3_f3d[];
extern Gfx vcutm_dl_eye_001_mesh_layer_1[];
extern Gfx vcutm_dl_eye_002_mesh_layer_1[];
extern Gfx vcutm_dl_material_revert_render_settings[];
