extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_001[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_002[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_003[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_004[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_005[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_006[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_007[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_008[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_009[];
extern const GeoLayout castle_grounds_area_2_geo[];
extern const GeoLayout castle_grounds_area_2[];
extern const Collision castle_grounds_area_2_collision[];
extern const MacroObject castle_grounds_area_2_macro_objs[];
extern Lights1 castle_grounds_dl__auto__f3d_lights;
extern Lights1 castle_grounds_dl__auto_3_f3d_lights;
extern Lights1 castle_grounds_dl__auto_4_f3d_layer1_lights;
extern Lights1 castle_grounds_dl_f3d_material_lights;
extern Lights1 castle_grounds_dl_f3d_material_001_lights;
extern Lights1 castle_grounds_dl__3_f3d_lights;
extern Lights1 castle_grounds_dl__2_f3d_lights;
extern Lights1 castle_grounds_dl__4_f3d_lights;
extern Lights1 castle_grounds_dl___f3d_lights;
extern Lights1 castle_grounds_dl__7_f3d_lights;
extern Lights1 castle_grounds_dl__6_f3d_lights;
extern Lights1 castle_grounds_dl__1_f3d_lights;
extern Lights1 castle_grounds_dl__5_f3d_lights;
extern Lights1 castle_grounds_dl__8_f3d_lights;
extern u8 castle_grounds_dl__auto__i8[];
extern u8 castle_grounds_dl__auto_3_i8[];
extern u8 castle_grounds_dl__auto_4_rgba16[];
extern u8 castle_grounds_dl__auto_5_rgba16[];
extern u8 castle_grounds_dl__5_zz50_027_ia8[];
extern u8 castle_grounds_dl__5_zz50_020_ia8[];
extern u8 castle_grounds_dl__3_ci8[];
extern u8 castle_grounds_dl__3_ci8_pal_rgba16[];
extern u8 castle_grounds_dl__2_ci4[];
extern u8 castle_grounds_dl__2_ci4_pal_rgba16[];
extern u8 castle_grounds_dl__4_ci8[];
extern u8 castle_grounds_dl__4_ci8_pal_rgba16[];
extern u8 castle_grounds_dl___ci4[];
extern u8 castle_grounds_dl___ci4_pal_rgba16[];
extern u8 castle_grounds_dl__7_ci4[];
extern u8 castle_grounds_dl__7_ci4_pal_rgba16[];
extern u8 castle_grounds_dl__6_ci4[];
extern u8 castle_grounds_dl__6_ci4_pal_rgba16[];
extern u8 castle_grounds_dl__1_ci4[];
extern u8 castle_grounds_dl__1_ci4_pal_rgba16[];
extern u8 castle_grounds_dl__5_ci4[];
extern u8 castle_grounds_dl__5_ci4_pal_rgba16[];
extern u8 castle_grounds_dl__8_ci4[];
extern u8 castle_grounds_dl__8_ci4_pal_rgba16[];
extern Vtx castle_grounds_dl_b2_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_b2_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_b2_mesh_layer_1_vtx_1[36];
extern Gfx castle_grounds_dl_b2_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_b2_mesh_layer_1_vtx_2[22];
extern Gfx castle_grounds_dl_b2_mesh_layer_1_tri_2[];
extern Vtx castle_grounds_dl_flower0_mesh_layer_5_vtx_0[40];
extern Gfx castle_grounds_dl_flower0_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_flower1_mesh_layer_5_vtx_0[40];
extern Gfx castle_grounds_dl_flower1_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_flower2_mesh_layer_5_vtx_0[40];
extern Gfx castle_grounds_dl_flower2_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_flower3_mesh_layer_5_vtx_0[40];
extern Gfx castle_grounds_dl_flower3_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_flower4_mesh_layer_5_vtx_0[40];
extern Gfx castle_grounds_dl_flower4_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_flower5_mesh_layer_5_vtx_0[40];
extern Gfx castle_grounds_dl_flower5_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_flower6_mesh_layer_5_vtx_0[40];
extern Gfx castle_grounds_dl_flower6_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_flower7_mesh_layer_5_vtx_0[40];
extern Gfx castle_grounds_dl_flower7_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_flower8_mesh_layer_5_vtx_0[40];
extern Gfx castle_grounds_dl_flower8_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_flower9_mesh_layer_5_vtx_0[40];
extern Gfx castle_grounds_dl_flower9_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_LAVA_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_LAVA_mesh_layer_1_vtx_0[111];
extern Gfx castle_grounds_dl_LAVA_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_LAVA_mesh_layer_1_vtx_1[50];
extern Gfx castle_grounds_dl_LAVA_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_LAVA_mesh_layer_1_vtx_2[210];
extern Gfx castle_grounds_dl_LAVA_mesh_layer_1_tri_2[];
extern Vtx castle_grounds_dl_LAVA_mesh_layer_1_vtx_3[111];
extern Gfx castle_grounds_dl_LAVA_mesh_layer_1_tri_3[];
extern Vtx castle_grounds_dl_LAVA_mesh_layer_1_vtx_4[94];
extern Gfx castle_grounds_dl_LAVA_mesh_layer_1_tri_4[];
extern Vtx castle_grounds_dl_LAVA_mesh_layer_1_vtx_5[52];
extern Gfx castle_grounds_dl_LAVA_mesh_layer_1_tri_5[];
extern Vtx castle_grounds_dl_LAVA_mesh_layer_1_vtx_6[27];
extern Gfx castle_grounds_dl_LAVA_mesh_layer_1_tri_6[];
extern Vtx castle_grounds_dl_LAVA_mesh_layer_1_vtx_7[36];
extern Gfx castle_grounds_dl_LAVA_mesh_layer_1_tri_7[];
extern Vtx castle_grounds_dl_LAVA_mesh_layer_1_vtx_8[24];
extern Gfx castle_grounds_dl_LAVA_mesh_layer_1_tri_8[];
extern Gfx mat_castle_grounds_dl__auto__f3d[];
extern Gfx mat_revert_castle_grounds_dl__auto__f3d[];
extern Gfx mat_castle_grounds_dl__auto_3_f3d[];
extern Gfx mat_revert_castle_grounds_dl__auto_3_f3d[];
extern Gfx mat_castle_grounds_dl__auto_4_f3d_layer1[];
extern Gfx mat_revert_castle_grounds_dl__auto_4_f3d_layer1[];
extern Gfx mat_castle_grounds_dl_f3d_material[];
extern Gfx mat_revert_castle_grounds_dl_f3d_material[];
extern Gfx mat_castle_grounds_dl_f3d_material_001[];
extern Gfx mat_revert_castle_grounds_dl_f3d_material_001[];
extern Gfx mat_castle_grounds_dl__3_f3d[];
extern Gfx mat_revert_castle_grounds_dl__3_f3d[];
extern Gfx mat_castle_grounds_dl__2_f3d[];
extern Gfx mat_revert_castle_grounds_dl__2_f3d[];
extern Gfx mat_castle_grounds_dl__4_f3d[];
extern Gfx mat_revert_castle_grounds_dl__4_f3d[];
extern Gfx mat_castle_grounds_dl___f3d[];
extern Gfx mat_revert_castle_grounds_dl___f3d[];
extern Gfx mat_castle_grounds_dl__7_f3d[];
extern Gfx mat_revert_castle_grounds_dl__7_f3d[];
extern Gfx mat_castle_grounds_dl__6_f3d[];
extern Gfx mat_revert_castle_grounds_dl__6_f3d[];
extern Gfx mat_castle_grounds_dl__1_f3d[];
extern Gfx mat_revert_castle_grounds_dl__1_f3d[];
extern Gfx mat_castle_grounds_dl__5_f3d[];
extern Gfx mat_revert_castle_grounds_dl__5_f3d[];
extern Gfx mat_castle_grounds_dl__8_f3d[];
extern Gfx mat_revert_castle_grounds_dl__8_f3d[];
extern Gfx castle_grounds_dl_b2_mesh_layer_1[];
extern Gfx castle_grounds_dl_flower0_mesh_layer_5[];
extern Gfx castle_grounds_dl_flower1_mesh_layer_5[];
extern Gfx castle_grounds_dl_flower2_mesh_layer_5[];
extern Gfx castle_grounds_dl_flower3_mesh_layer_5[];
extern Gfx castle_grounds_dl_flower4_mesh_layer_5[];
extern Gfx castle_grounds_dl_flower5_mesh_layer_5[];
extern Gfx castle_grounds_dl_flower6_mesh_layer_5[];
extern Gfx castle_grounds_dl_flower7_mesh_layer_5[];
extern Gfx castle_grounds_dl_flower8_mesh_layer_5[];
extern Gfx castle_grounds_dl_flower9_mesh_layer_5[];
extern Gfx castle_grounds_dl_LAVA_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
