extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_001[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_002[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_003[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_004[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_005[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_006[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_007[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_008[];
extern const Trajectory castle_grounds_area_1_spline_mips_curve_009[];
extern Lights1 castle_grounds_dl__auto__f3d_lights;
extern Lights1 castle_grounds_dl__auto_3_f3d_lights;
extern Lights1 castle_grounds_dl__auto_4_f3d_layer1_lights;
extern u8 castle_grounds_dl__auto__i8[];
extern u8 castle_grounds_dl__auto_3_i8[];
extern u8 castle_grounds_dl__auto_4_rgba16[];
extern u8 castle_grounds_dl__auto_5_rgba16[];
extern Vtx castle_grounds_dl_b2_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_b2_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_b2_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_b2_mesh_layer_1_vtx_1[36];
extern Gfx castle_grounds_dl_b2_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_b2_mesh_layer_1_vtx_2[22];
extern Gfx castle_grounds_dl_b2_mesh_layer_1_tri_2[];
extern Gfx mat_castle_grounds_dl__auto__f3d[];
extern Gfx mat_revert_castle_grounds_dl__auto__f3d[];
extern Gfx mat_castle_grounds_dl__auto_3_f3d[];
extern Gfx mat_revert_castle_grounds_dl__auto_3_f3d[];
extern Gfx mat_castle_grounds_dl__auto_4_f3d_layer1[];
extern Gfx mat_revert_castle_grounds_dl__auto_4_f3d_layer1[];
extern Gfx castle_grounds_dl_b2_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
