#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"
#include "levels/castle_grounds/texture.inc.c"
#include "levels/castle_grounds/areas/1/1/model.inc.c"
#include "levels/castle_grounds/areas/1/2/model.inc.c"
#include "levels/castle_grounds/areas/1/3/model.inc.c"
#include "levels/castle_grounds/areas/1/4/model.inc.c"
#include "levels/castle_grounds/areas/1/5/model.inc.c"
#include "levels/castle_grounds/areas/1/6/model.inc.c"
#include "levels/castle_grounds/areas/1/7/model.inc.c"
#include "levels/castle_grounds/areas/1/8/model.inc.c"
#include "levels/castle_grounds/areas/1/9/model.inc.c"
#include "levels/castle_grounds/areas/1/10/model.inc.c"
#include "levels/castle_grounds/areas/1/11/model.inc.c"
#include "levels/castle_grounds/areas/1/11/anim.inc.c"
#include "levels/castle_grounds/areas/1/12/model.inc.c" // Letter
#ifndef VERSION_JP
#include "levels/castle_grounds/areas/1/13/model.inc.c" // Peach signature
#endif
#include "levels/castle_grounds/areas/1/collision.inc.c"
#include "levels/castle_grounds/areas/1/macro.inc.c"
#include "levels/castle_grounds/areas/1/7/collision.inc.c"
#include "levels/castle_grounds/areas/1/8/collision.inc.c"
#include "levels/castle_grounds/areas/1/movtext.inc.c"

#include "levels/castle_grounds/leveldata.inc.c"

#include "levels/castle_grounds/panel0/model.inc.c"
#include "levels/castle_grounds/panel1/model.inc.c"
#include "levels/castle_grounds/panel2/model.inc.c"
#include "levels/castle_grounds/panel3/model.inc.c"
#include "levels/castle_grounds/panel4/model.inc.c"
#include "levels/castle_grounds/panel5/model.inc.c"
#include "levels/castle_grounds/panel6/model.inc.c"
#include "levels/castle_grounds/panel7/model.inc.c"
#include "levels/castle_grounds/panel8/model.inc.c"
#include "levels/castle_grounds/panel9/model.inc.c"
#include "levels/castle_grounds/textL/model.inc.c"
#include "levels/castle_grounds/textR/model.inc.c"