extern const GeoLayout sa_area_1_geo[];
extern const GeoLayout sa_area_1[];
extern const Collision sa_area_1_collision[];
extern const MacroObject sa_area_1_macro_objs[];
extern Lights1 sa_dl__auto_5_f3d_lights;
extern Lights1 sa_dl__auto_4_f3d_lights;
extern Lights1 sa_dl__1_f3d_lights;
extern Lights1 sa_dl__2_f3d_lights;
extern Lights1 sa_dl__3_f3d_lights;
extern u8 sa_dl__auto_5_ci4[];
extern u8 sa_dl__auto_5_ci4_pal_rgba16[];
extern u8 sa_dl__auto_4_i8[];
extern u8 sa_dl__1_ci4[];
extern u8 sa_dl__1_ci4_pal_rgba16[];
extern u8 sa_dl__2_ci4[];
extern u8 sa_dl__2_ci4_pal_rgba16[];
extern u8 sa_dl__3_ci4[];
extern u8 sa_dl__3_ci4_pal_rgba16[];
extern Vtx sa_dl_eye_002_mesh_layer_1_vtx_cull[8];
extern Vtx sa_dl_eye_002_mesh_layer_1_vtx_0[45] __attribute__((section(".data")));
extern Gfx sa_dl_eye_002_mesh_layer_1_tri_0[];
extern Vtx sa_dl_eye_002_mesh_layer_1_vtx_1[48];
extern Gfx sa_dl_eye_002_mesh_layer_1_tri_1[];
extern Vtx sa_dl_eye_002_mesh_layer_1_vtx_2[26];
extern Gfx sa_dl_eye_002_mesh_layer_1_tri_2[];
extern Vtx sa_dl_eye_002_mesh_layer_1_vtx_3[10];
extern Gfx sa_dl_eye_002_mesh_layer_1_tri_3[];
extern Vtx sa_dl_eye_002_mesh_layer_1_vtx_4[12];
extern Gfx sa_dl_eye_002_mesh_layer_1_tri_4[];
extern Gfx mat_sa_dl__auto_5_f3d[];
extern Gfx mat_revert_sa_dl__auto_5_f3d[];
extern Gfx mat_sa_dl__auto_4_f3d[];
extern Gfx mat_revert_sa_dl__auto_4_f3d[];
extern Gfx mat_sa_dl__1_f3d[];
extern Gfx mat_revert_sa_dl__1_f3d[];
extern Gfx mat_sa_dl__2_f3d[];
extern Gfx mat_revert_sa_dl__2_f3d[];
extern Gfx mat_sa_dl__3_f3d[];
extern Gfx mat_revert_sa_dl__3_f3d[];
extern Gfx sa_dl_eye_002_mesh_layer_1[];
extern Gfx sa_dl_material_revert_render_settings[];
