#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/spiders/leveldata.inc.c"

#include "levels/spiders/spiders_bee/model.inc.c"
#include "levels/spiders/spiders_bee_angy/model.inc.c"
#include "levels/spiders/spiders_bee_blue/model.inc.c"
#include "levels/spiders/spiders_bee_boardos/model.inc.c"
#include "levels/spiders/spiders_bee_boardos/collision.inc.c"
#include "levels/spiders/spiders_waterfally_nest/model.inc.c"
#include "levels/spiders/spiders_waterfally_pa/model.inc.c"
#include "levels/spiders/spiders_waterfally_pa/collision.inc.c"
#include "levels/spiders/spiders_waterfally_pb/model.inc.c"
#include "levels/spiders/spiders_waterfally_pb/collision.inc.c"
#include "levels/spiders/waterfally_switch/model.inc.c"
#include "levels/spiders/waterfally_switchblock/model.inc.c"
#include "levels/spiders/waterfally_switchblock/collision.inc.c"
#include "levels/spiders/waterfally_switch/collision.inc.c"
#include "levels/spiders/spiders_cage/collision.inc.c"
#include "levels/spiders/spiders_cage/model.inc.c"
#include "levels/spiders/spiders_comb/model.inc.c"
#include "levels/spiders/spiders_arrow/model.inc.c"