extern const GeoLayout triarc_plat0_geo[];
extern Lights1 triarc_plat0_Stoney_lights;
extern Lights1 triarc_plat0_Grass_lights;
extern u8 triarc_plat0_Skysland_ci8[];
extern u8 triarc_plat0_Skysland_ci8_pal_rgba16[];
extern u8 triarc_plat0_Grass_ci8[];
extern u8 triarc_plat0_Grass_ci8_pal_rgba16[];
extern Vtx triarc_plat0_Cylinder_006_mesh_layer_1_vtx_cull[8];
extern Vtx triarc_plat0_Cylinder_006_mesh_layer_1_vtx_0[31];
extern Gfx triarc_plat0_Cylinder_006_mesh_layer_1_tri_0[];
extern Vtx triarc_plat0_Cylinder_006_mesh_layer_1_vtx_1[12];
extern Gfx triarc_plat0_Cylinder_006_mesh_layer_1_tri_1[];
extern Gfx mat_triarc_plat0_Stoney[];
extern Gfx mat_revert_triarc_plat0_Stoney[];
extern Gfx mat_triarc_plat0_Grass[];
extern Gfx mat_revert_triarc_plat0_Grass[];
extern Gfx triarc_plat0_Cylinder_006_mesh_layer_1[];
extern Gfx triarc_plat0_material_revert_render_settings[];
