extern const GeoLayout tube1_geo[];
extern Lights1 tube1__13_f3d_layer1_lights;
extern u8 tube1__13_ci4[];
extern u8 tube1__13_ci4_pal_rgba16[];
extern Vtx tube1_c3_tube_mesh_layer_1_vtx_cull[8];
extern Vtx tube1_c3_tube_mesh_layer_1_vtx_0[26];
extern Gfx tube1_c3_tube_mesh_layer_1_tri_0[];
extern Gfx mat_tube1__13_f3d_layer1[];
extern Gfx mat_revert_tube1__13_f3d_layer1[];
extern Gfx tube1_c3_tube_mesh_layer_1[];
extern Gfx tube1_material_revert_render_settings[];
