extern const GeoLayout triarc_rock_geo[];
extern Lights1 triarc_rock_f3d_material_001_layer5_lights;
extern u8 triarc_rock__0E000010_i8[];
extern Vtx triarc_rock_rock_mesh_layer_5_vtx_cull[8];
extern Vtx triarc_rock_rock_mesh_layer_5_vtx_0[37];
extern Gfx triarc_rock_rock_mesh_layer_5_tri_0[];
extern Gfx mat_triarc_rock_f3d_material_001_layer5[];
extern Gfx mat_revert_triarc_rock_f3d_material_001_layer5[];
extern Gfx triarc_rock_rock_mesh_layer_5[];
extern Gfx triarc_rock_material_revert_render_settings[];
