extern const GeoLayout luigiman_airlock_door_geo[];
extern Lights1 luigiman_airlock_door_Ceiling_lights;
extern u8 luigiman_airlock_door__3588144___Copy_i8[];
extern Vtx luigiman_airlock_door_Airlock_Door_mesh_layer_1_vtx_0[24];
extern Gfx luigiman_airlock_door_Airlock_Door_mesh_layer_1_tri_0[];
extern Gfx mat_luigiman_airlock_door_Ceiling[];
extern Gfx luigiman_airlock_door_Airlock_Door_mesh_layer_1[];
extern Gfx luigiman_airlock_door_material_revert_render_settings[];
