#include "src/game/envfx_snow.h"

const GeoLayout rovert_area_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, rovert_dl_Cylinder_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, rovert_dl_Cylinder_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, rovert_dl_Cylinder_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, rovert_dl_nonsolid_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, rovert_dl_nonsolid_001_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, rovert_dl_nonsolid_001_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout rovert_area_2[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_BELOW_CLOUDS, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, -39702, 0, -100, -39702, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, rovert_area_2_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, rovert_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, rovert_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, rovert_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, rovert_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
