#include "src/game/envfx_snow.h"

const GeoLayout rovert_area_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, 0, -298, rovert_dl__decor_002_mesh_layer_5),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, rovert_dl__decor_002_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, -3467, -298, rovert_dl__decor1_001_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, -3467, -298, rovert_dl__decor2_001_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 6648, 3043, -7606, 0, 45, 0, rovert_dl_cloudpuff_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 5510, 3092, -246, 0, 45, 0, rovert_dl_cloudpuff_001_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 4805, 2864, -914, 0, -180, 0, rovert_dl_cloudpuff_002_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 5015, 3512, 584, 0, -180, 0, rovert_dl_cloudpuff_003_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 52, 1119, 1984, 0, -180, 0, rovert_dl_cloudpuff_004_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, -2293, 4092, -9654, 0, -180, 0, rovert_dl_cloudpuff_005_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, -2954, 4377, -9963, 0, -180, 0, rovert_dl_cloudpuff_006_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, -3368, 4837, -9275, 0, -180, 0, rovert_dl_cloudpuff_007_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, -3483, 6036, -7752, 0, -180, 0, rovert_dl_cloudpuff_008_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, -3488, 6420, -6869, 0, -180, 0, rovert_dl_cloudpuff_009_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 0, 0, -298, rovert_dl_cylin_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, rovert_dl_cylin_mesh_layer_5),
			GEO_DISPLAY_LIST(LAYER_ALPHA, rovert_dl_cylin_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, rovert_dl_Cylinder_001_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_ALPHA, rovert_dl_Cylinder_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, rovert_dl_Cylinder_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, 0, 39702, rovert_dl_Cylinder_004_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, rovert_dl_nonsolid_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, rovert_dl_nonsolid_001_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, rovert_dl_nonsolid_001_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout rovert_area_2[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_BELOW_CLOUDS, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 40000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, -39702, 0, -100, -39702, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, rovert_area_2_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, rovert_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, rovert_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, rovert_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, rovert_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
