extern const GeoLayout triarc_plat1_geo[];
extern Lights1 triarc_plat1_Stoney_lights;
extern Lights1 triarc_plat1_Leaves_001_lights;
extern u8 triarc_plat1_Skysland_ci8[];
extern u8 triarc_plat1_Skysland_ci8_pal_rgba16[];
extern u8 triarc_plat1_FutureLeaves_rgba16[];
extern Vtx triarc_plat1_cylin_001_mesh_layer_1_vtx_0[31];
extern Gfx triarc_plat1_cylin_001_mesh_layer_1_tri_0[];
extern Vtx triarc_plat1_cylin_001_mesh_layer_1_vtx_1[12];
extern Gfx triarc_plat1_cylin_001_mesh_layer_1_tri_1[];
extern Gfx mat_triarc_plat1_Stoney[];
extern Gfx mat_revert_triarc_plat1_Stoney[];
extern Gfx mat_triarc_plat1_Leaves_001[];
extern Gfx mat_revert_triarc_plat1_Leaves_001[];
extern Gfx triarc_plat1_cylin_001_mesh_layer_1[];
extern Gfx triarc_plat1_material_revert_render_settings[];
