#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/rng/leveldata.inc.c"

#include "levels/rng/rng_mushroom/model.inc.c"
#include "levels/rng/rng_mushroom/collision.inc.c"
#include "levels/rng/rng_pyramid/model.inc.c"
#include "levels/rng/rng_pyramid/collision.inc.c"
#include "levels/rng/rng_shape1/collision.inc.c"
#include "levels/rng/rng_shape1/model.inc.c"
#include "levels/rng/rng_shape2/model.inc.c"
#include "levels/rng/rng_shape3/model.inc.c"
#include "levels/rng/rng_shape3/collision.inc.c"
#include "levels/rng/rng_shape4/model.inc.c"
#include "levels/rng/rng_shape4/collision.inc.c"
#include "levels/rng/rng_shape2/collision.inc.c"
#include "levels/rng/rng_cactus/model.inc.c"
#include "levels/rng/rng_cactus2/model.inc.c"
#include "levels/rng/rng_cactus/collision.inc.c"
#include "levels/rng/rng_cactus2/collision.inc.c"
#include "levels/rng/rng_lamp/model.inc.c"
#include "levels/rng/rng_lamp/collision.inc.c"