extern void scroll_bob_dl_golfer_mesh_layer_1_vtx_18();
extern void scroll_gfx_mat_bob_dl__53_f3d();
extern void scroll_gfx_mat_bob_dl__17_f3d();
extern void scroll_gfx_mat_bob_dl__29_f3d();
extern void scroll_gfx_mat_bob_dl__50_f3d();
extern void scroll_gfx_mat_bob_dl__8_f3d();
extern void scroll_gfx_mat_bob_dl_move2();
extern void scroll_gfx_mat_bob_dl_move();
extern void scroll_bob();
