extern const GeoLayout spiders_cage_geo[];
extern Lights1 spiders_cage__1_011_f3d_lights;
extern u8 spiders_cage__1_ci8[];
extern u8 spiders_cage__1_ci8_pal_rgba16[];
extern Vtx spiders_cage_waterfally_cage_mesh_layer_4_vtx_cull[8];
extern Vtx spiders_cage_waterfally_cage_mesh_layer_4_vtx_0[6];
extern Gfx spiders_cage_waterfally_cage_mesh_layer_4_tri_0[];
extern Gfx mat_spiders_cage__1_011_f3d[];
extern Gfx mat_revert_spiders_cage__1_011_f3d[];
extern Gfx spiders_cage_waterfally_cage_mesh_layer_4[];
extern Gfx spiders_cage_material_revert_render_settings[];
