extern const GeoLayout blackspin_geo[];
extern Lights1 blackspin__51_f3d_lights;
extern u8 blackspin__51_ci4[];
extern u8 blackspin__51_pal_rgba16[];
extern Vtx blackspin_spinner_mesh_layer_1_vtx_cull[8];
extern Vtx blackspin_spinner_mesh_layer_1_vtx_0[31];
extern Gfx blackspin_spinner_mesh_layer_1_tri_0[];
extern Gfx mat_blackspin__51_f3d[];
extern Gfx mat_revert_blackspin__51_f3d[];
extern Gfx blackspin_spinner_mesh_layer_1[];
