#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/luigiman/leveldata.inc.c"

#include "levels/luigiman/luigiman_rings/model.inc.c"
#include "levels/luigiman/luigiman_rings/collision.inc.c"
#include "levels/luigiman/luigiman_spinning_holes1/model.inc.c"
#include "levels/luigiman/luigiman_spinning_holes1/collision.inc.c"
#include "levels/luigiman/luigiman_moving_platform/collision.inc.c"
#include "levels/luigiman/luigiman_moving_platform/model.inc.c"
#include "levels/luigiman/luigiman_airlock_main/model.inc.c"
#include "levels/luigiman/luigiman_airlock_main/collision.inc.c"
#include "levels/luigiman/luigiman_airlock_door/collision.inc.c"
#include "levels/luigiman/luigiman_airlock_door/model.inc.c"