extern const GeoLayout wdroplet_geo[];
extern Lights1 wdroplet_f3dlite_material_006_lights __attribute__((section(".data")));
extern u8 wdroplet_droplet_rgba16[] __attribute__((section(".data")));
extern Vtx wdroplet_Plane_mesh_layer_4_vtx_cull[8] __attribute__((section(".data")));
extern Vtx wdroplet_Plane_mesh_layer_4_vtx_0[4] __attribute__((section(".data")));
extern Gfx wdroplet_Plane_mesh_layer_4_tri_0[] __attribute__((section(".data")));
extern Gfx mat_wdroplet_f3dlite_material_006[] __attribute__((section(".data")));
extern Gfx mat_revert_wdroplet_f3dlite_material_006[] __attribute__((section(".data")));
extern Gfx wdroplet_Plane_mesh_layer_4[] __attribute__((section(".data")));
