#include "src/game/envfx_snow.h"

const GeoLayout bob_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -7631, 7821, 3745, bob_dl__bg_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_c1_a1_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_level_02_002_mesh_layer_4),
		GEO_CULL(-10500, 20000, -20000, 20000, -20000, 1200),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_level_02_003_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_level_02_003_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_level_02_004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_level_02_004_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_level_02_005_mesh_layer_4),
		GEO_CULL(-20000, -6500, -20000, 20000, -20000, 20000),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_level_1_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_level_1_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_CULL(-10000, 0, -20000, 20000, 0, 32000),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_level_2_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_level_2_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, -57, 0),
		GEO_OPEN_NODE(),
			GEO_CULL(-10000, 0, -20000, 20000, 0, 32000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bob_dl_level_2_001_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_CULL(-6500, 20000, -20000, 20000, -20000, 20000),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_level_3_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_CULL(-6500, 20000, -20000, 20000, -20000, 20000),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_level_3_s_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_level_3_s_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_level_3things_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_lvl_1flower_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bob_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -230, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bob_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bob_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bob_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bob_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
