COURSE_ACTS(COURSE_BOB, _(" 1 GOOMBA VALLEY"),
       _("EXPLORE THE CAVERNS...")     , _("SLIDIN' TO THE POLES") , _("THE VALLEY MIDWAY POINT"),
       _("AT THE END OF THE LAVA SOURCE")          , _("SHELL ACTION ON THE LAVA POOL")        , _("FLIGHT INTO FIVE SECRETS"))

COURSE_ACTS(COURSE_WF, _(" 2 POISONED WINTER"),
       _("SEEK THE ABANDONED HOUSE")        , _("THE TOP OF THE MOUNTAIN")    , _("SCARY SPINNING MADNESS"),
       _("THE LONELY STAR"), _("CHECK THE METAL CAP")    , _("THE WEIRD TREE STRANGER"))

COURSE_ACTS(COURSE_JRB, _(" 3 BITTER BADLANDS"),
       _("ATTACK OF THE KILLER PIRANHA")    , _("DIVE IN THE ROTATING CHALLENGE") , _("A VISIT IN THE STRANGE BUILDING"),
       _("BITTERING RED COINS OF THE LAKE")  , _("FLOWERY SEARCH FOR SECRETS")     , _("ABOVE THE CREEPY VOID"))

COURSE_ACTS(COURSE_CCM, _(" 4 STRANGE SEWERS"),
       _("TRY OUT THE GATE CONTROL")             , _("SECRETS ABOVE THE DRIED WASTE")             , _("RED ROOM FLOOD STRATS"),
       _("THE OLD SUNKEN SWITCH")  , _("VANISH CAP RUN THROUGH THE SEWERS")       , _("RIGHT ABOVE THE START"))

COURSE_ACTS(COURSE_BBH, _(" 5 AMPERSAND FURNACE"),
       _("A RIDE ON THE ARROW PLATFORM")            , _("FIREBALLS SHOW THE WAY") , _("IT IS ABOUT BURNING"),
       _("RIDE THE ANCIENT BEAST FOR 8 COINS")          , _("THE BULLET HELL")             , _("WIGGLER'S RAGE ATTACK"))

COURSE_ACTS(COURSE_HMC, _(" 6 "),
       _("SWIMMING BEAST IN THE CAVERN")  , _("ELEVATE FOR 8 RED COINS")       , _("METAL-HEAD MARIO CAN MOVE!"),
       _("NAVIGATING THE TOXIC MAZE")     , _("A-MAZE-ING EMERGENCY EXIT")     , _("WATCH FOR ROLLING ROCKS"))

COURSE_ACTS(COURSE_LLL, _(" 7 "),
       _("BOIL THE BIG BULLY")            , _("BULLY THE BULLIES")             , _("8-COIN PUZZLE WITH 15 PIECES"),
       _("RED-HOT LOG ROLLING")           , _("HOT-FOOT-IT INTO THE VOLCANO")  , _("ELEVATOR TOUR IN THE VOLCANO"))

COURSE_ACTS(COURSE_SSL, _(" 8 "),
       _("IN THE TALONS OF THE BIG BIRD") , _("SHINING ATOP THE PYRAMID")      , _("INSIDE THE ANCIENT PYRAMID"),
       _("STAND TALL ON THE FOUR PILLARS"), _("FREE FLYING FOR 8 RED COINS")   , _("PYRAMID PUZZLE"))

COURSE_ACTS(COURSE_DDD, _(" 9 "),
       _("BOARD BOWSER'S SUB")            , _("CHESTS IN THE CURRENT")         , _("POLE-JUMPING FOR RED COINS"),
       _("THROUGH THE JET STREAM")        , _("THE MANTA RAY'S REWARD")        , _("COLLECT THE CAPS..."))

COURSE_ACTS(COURSE_SL, _("10 "),
       _("SNOWMAN'S BIG HEAD")            , _("CHILL WITH THE BULLY")          , _("IN THE DEEP FREEZE"),
       _("WHIRL FROM THE FREEZING POND")  , _("SHELL SHREDDIN' FOR RED COINS") , _("INTO THE IGLOO"))

COURSE_ACTS(COURSE_WDW, _("11 "),
       _("SHOCKING ARROW LIFTS!")         , _("TOP O' THE TOWN")               , _("SECRETS IN THE SHALLOWS & SKY"),
       _("EXPRESS ELEVATOR--HURRY UP!")   , _("GO TO TOWN FOR RED COINS")      , _("QUICK RACE THROUGH DOWNTOWN!"))

COURSE_ACTS(COURSE_TTM, _("12 "),
       _("SCALE THE MOUNTAIN")            , _("MYSTERY OF THE MONKEY CAGE")    , _("SCARY 'SHROOMS, RED COINS"),
       _("MYSTERIOUS MOUNTAINSIDE")       , _("BREATHTAKING VIEW FROM BRIDGE") , _("BLAST TO THE LONELY MUSHROOM"))

COURSE_ACTS(COURSE_THI, _("13 "),
       _("PLUCK THE PIRANHA FLOWER")      , _("THE TIP TOP OF THE HUGE ISLAND"), _("REMATCH WITH KOOPA THE QUICK"),
       _("FIVE ITTY BITTY SECRETS")       , _("WIGGLER'S RED COINS")           , _("MAKE WIGGLER SQUIRM"))

COURSE_ACTS(COURSE_TTC, _("14 "),
       _("ROLL INTO THE CAGE")            , _("THE PIT AND THE PENDULUMS")     , _("GET A HAND"),
       _("STOMP ON THE THWOMP")           , _("TIMED JUMPS ON MOVING BARS")    , _("STOP TIME FOR RED COINS"))

COURSE_ACTS(COURSE_RR, _("15 "),
       _("CRUISER CROSSING THE RAINBOW")  , _("THE BIG HOUSE IN THE SKY")      , _("COINS AMASSED IN A MAZE"),
       _("SWINGIN' IN THE BREEZE")        , _("TRICKY TRIANGLES!")             , _("SOMEWHERE OVER THE RAINBOW"))

SECRET_STAR(COURSE_BITDW, _("   SPEEDY TRIALS CHALLENGE"))
SECRET_STAR(COURSE_BITFS, _("   VS. BIG BULLY"))
SECRET_STAR(COURSE_BITS, _("   KING BOB-OMB'S FORTRESS"))
SECRET_STAR(COURSE_PSS, _("   SCARY SECRET SLIDE"))
SECRET_STAR(COURSE_COTMC, _("   TROPICAL RESORT"))
SECRET_STAR(COURSE_TOTWC, _("   RAINBOW HEAVENS"))
SECRET_STAR(COURSE_VCUTM, _("   TWIN ARENAS"))
SECRET_STAR(COURSE_WMOTR, _("   100 COINS IN A LAVA WASTELAND"))
SECRET_STAR(COURSE_SA, _("   VS. MR. I"))
SECRET_STAR(COURSE_CAKE_END, _("   VS. KING BOB-OMB"))

CASTLE_SECRET_STARS(_("   IMPRISONED SECRET STARS"))

EXTRA_TEXT(0, _("ONE OF THE STARS OF THE JAIL!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
