COURSE_ACTS(COURSE_BOB, _(" 1 BOB-OMB PLAINS"),	_("DEFEAT KING BOB-OMB... AGAIN!"),	_("ON TOP OF THE WINDMILL"),	_("BEHIND BARS"),	_("FIND THE 8 RED COINS"),	_("UPON A HILL"),	_("SKY-HIGH SECRETS -WC-"))

COURSE_ACTS(COURSE_WF, _(" 2 WHOMP'S FOREST"),	_("THE WHOMP KING'S REVENGE"),	_("INSIDE THE GIANT TREE"),	_("EXPLORE DEEP INTO THE FOREST"),	_("THE FOREST'S RED COINS"),	_("CLIMB THE FOREST MUSHROOMS -WC-"),	_("UPON THE NOT-SO WATERFALL -WC-"))

COURSE_ACTS(COURSE_JRB, _(" 3 CALIGNOUS COVE"),	_("DIVE DOWN TO GREAT DEPTHS"),	_("HIDDEN IN THE CORAL"),	_("METAL MARIO IN THE HIDDEN ROOM -MC-"),	_("AT THE TOP OF THE CAVE"),	_("UNDERWATER HUNT FOR RED COINS"),	_("PURPLE SWITCHIN' BOXES"))

COURSE_ACTS(COURSE_CCM, _(" 4 SNOW STORM PEAKS"),	_("SECRETS IN THE CAVE"),	_("KING OF THE MOUNTAIN"),	_("SPIN TO THE LONESOME ISLAND"),	_("FIND THE BABY PENGUIN"),	_("ICY RED COINS"),	_("UNDERWATER TRAP"))

COURSE_ACTS(COURSE_BBH, _(" 5 FIERY FACTORY"),	_("BURN THE BIG BULLY"),	_("CLIMB THE FACTORY"),	_("COGS AND CONVEYOR BELTS"),	_("COLLECT THE RED COINS"),	_("INSIDE THE RUSTY PIPE"),	_("THE FACTORY'S SECRET STAR"))

COURSE_ACTS(COURSE_HMC, _(" 6 BOO'S TREMBLING TOWER"),	_("CLIMB TO THE TOWER TOP"),	_("COLLECT THE MYSTERIOUS KEYS"),	_("THE SPOOKY RED COINS"),	_("UPON THE SNAKE BLOCKS"),	_("BIG BOO'S FRIGHTENING RETURN"),	_("THE STARING CONTEST"))

COURSE_ACTS(COURSE_LLL, _(" 7 GIANT OVERGROWN GARDEN"),	_("HUNT THE PESKY PIRANHAS"),	_("ON TOP OF THE FLOWER"),	_("CLIMB TO THE GREENHOUSE ROOF"),	_("THE GIANT WATERING CAN"),	_("THE OVERGROWN RED COINS"),	_("INSIDE THE HEDGE MAZE"))

COURSE_ACTS(COURSE_SSL, _(" 8 SCORCHING DESERT"),	_("CLIMB THE PILLARS"),	_("INSIDE THE TEMPLE"),	_("ON TOP OF THE GIANT CACTUS"),	_("THE SANDY RED COINS"),	_("FLY TO THE TALL CENTER -WC-"),	_("SPINNING DIZZY MARIO"))

COURSE_ACTS(COURSE_DDD, _(" 9 SANDY SEASIDE BAY"),	_("TROUBLE IN THE HILLS"),	_("FLOOD THE UNDERWATER CAVE"),	_("THE BAY'S RED COINS"),	_("THE SHARPEST ROOF"),	_("HIDDEN STAR OF THE BAY"),	_("ON TOP OF THE LIGHTHOUSE"))

COURSE_ACTS(COURSE_SL, _("10 MOLTEN MAGMA GALAXY"),	_("BURN THE BIG BULLY AGAIN!"),	_("THE RED HOT HIDDEN BOXES"),	_("SIZZLING RED COINS"),	_("BOUNCING METAL ON LAVA PLANETS -MC-"),	_("SHOOT TO THE TALLEST PILLAR -WC-"),	_("THE UNDERGROUND SHELL RIDE!"))

COURSE_ACTS(COURSE_WDW, _("11 DARK DANK ABYSS"),	_("A BREATH OF FRESH AIR"),	_("THE ABYSS BOX CHALLENGE -MC-"),	_("THE STAR IN THE WALL"),	_("UNDERWATER PIPE MADNESS"),	_("FLOOD THE ABYSS FOR RED COINS"),	_("INSIDE THE CAGE"))

COURSE_ACTS(COURSE_TTM, _("12 PERILOUS CLIFFS"),	_("BEYOND THE RISKY PATH"),	_("THE CORNER OF THE CLIFFS"),	_("THE MIDDLE TOWER"),	_("AMONGST THE WALL JUMP CLIFF"),	_("SCALE THE TALLEST CLIFF"),	_("THE DANGEROUS RED COINS"))

COURSE_ACTS(COURSE_THI, _("13 MISTY MINE"),	_("CLIMBIN' THE RAILS"),	_("ELEVATOR RIDE FOR RED COINS"),	_("MISTY MINE'S TREACHEROUS SLIDE"),	_("THE LAVA-POOL HIDEOUT"),	_("THE LOST MINECART"),	_("DOWN THE SECRET TUNNEL"))

COURSE_ACTS(COURSE_TTC, _("14 CLOUDY QUADRANGLE"),	_("CLIMBING THROUGH THE CLOUDS"),	_("ASCEND THE BLIMP"),	_("KOOPA THE QUICK'S GRAND PRIX"),	_("SEEK THE RED COINS"),	_("JUMP DOWN THE CHIMNEY"),	_("TIME YOUR JUMP!"))

COURSE_ACTS(COURSE_RR, _("15 RAINBOW STAR HAVEN"),	_("FROM THE TOWERTOP TO THE STARS"),	_("THE SECRETS OF THE ISLANDS -WC-"),	_("AMONGST THE BLOCKY PATH"),	_("THE RED COINS OF THE STARS"),	_("MARIO'S BLOCKY PROBLEM"),	_("THE TOAD CAPTAIN'S PRESENT"))

SECRET_STAR(15, _("   FEARFUL FORTRESS"))
SECRET_STAR(16, _("   BLAZING THWOMP TOWER"))
SECRET_STAR(17, _("   BOWSER'S BATTLE BASE"))
SECRET_STAR(18, _("   NOSTALGIA SLIDE"))
SECRET_STAR(19, _("   FROST-INFERNO METAL CAP"))
SECRET_STAR(20, _("   THE WING CAP PALACE"))
SECRET_STAR(21, _("   VANISH CAP UNDER THE MOAT"))
SECRET_STAR(22, _("   THE END"))
SECRET_STAR(23, _("   THE SECRET ANCIENT TEMPLE"))
SECRET_STAR(24, _(""))
CASTLE_SECRET_STARS(_("   SECRET STARS"))
EXTRA_TEXT(0,_("YOU GOT A SECRET STAR!!"))
EXTRA_TEXT(1,_(""))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
