extern const GeoLayout bitfs_thing_geo[];
extern Lights1 bitfs_thing__4_f3d_lights;
extern u8 bitfs_thing__4_ci4[];
extern u8 bitfs_thing__4_ci4_pal_rgba16[];
extern Vtx bitfs_thing_bully_001_mesh_layer_1_vtx_cull[8];
extern Vtx bitfs_thing_bully_001_mesh_layer_1_vtx_0[20];
extern Gfx bitfs_thing_bully_001_mesh_layer_1_tri_0[];
extern Gfx mat_bitfs_thing__4_f3d[];
extern Gfx mat_revert_bitfs_thing__4_f3d[];
extern Gfx bitfs_thing_bully_001_mesh_layer_1[];
extern Gfx bitfs_thing_material_revert_render_settings[];
