#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/rovert/leveldata.inc.c"

#include "levels/rovert/fluxpool/model.inc.c"
#include "levels/rovert/rovert_pushable/collision.inc.c"
#include "levels/rovert/rovert_pushable/model.inc.c"
#include "levels/rovert/watch/model.inc.c"
#include "levels/rovert/watch2/model.inc.c"
#include "levels/rovert/watch3/model.inc.c"
#include "levels/rovert/watch4/model.inc.c"
#include "levels/rovert/watch5/model.inc.c"
#include "levels/rovert/rovert_gear/collision.inc.c"
#include "levels/rovert/rovert_gear1/model.inc.c"
#include "levels/rovert/rovert_gear2/model.inc.c"
#include "levels/rovert/rovert_hyperblock/model.inc.c"
#include "levels/rovert/rovert_hyperblock/collision.inc.c"
#include "levels/rovert/rovert_gate/collision.inc.c"
#include "levels/rovert/rovert_gate/model.inc.c"
#include "levels/rovert/rovert_wball/model.inc.c"