#include "levels/rovert/texture_include.inc.c"
#include "levels/rovert/area_2/collision.inc.c"
#include "levels/rovert/area_2/macro.inc.c"
#include "levels/rovert/area_2/spline.inc.c"
#include "levels/rovert/area_1/collision.inc.c"
#include "levels/rovert/area_1/macro.inc.c"
#include "levels/rovert/area_1/spline.inc.c"
#include "levels/rovert/model.inc.c"
