extern void scroll_castle_inside_dl_tower_mesh_layer_1_vtx_21();
extern void scroll_castle_inside_dl_tower_005_mesh_layer_4_vtx_0();
extern void scroll_castle_inside_dl_tower_006_mesh_layer_5_vtx_0();
extern void scroll_castle_inside_dl_tower_007_mesh_layer_5_vtx_0();
extern void scroll_castle_inside_dl_water_mesh_layer_5_vtx_0();
extern void scroll_castle_inside_dl_waterbox2_mesh_layer_5_vtx_0();
extern void scroll_castle_inside();
