extern const GeoLayout bitfs_area_1_geo[];
extern const GeoLayout bitfs_area_1[];
extern const Collision bitfs_area_1_collision[];
extern const MacroObject bitfs_area_1_macro_objs[];
extern Lights1 bitfs_dl__auto_5_f3d_lights;
extern Lights1 bitfs_dl__auto_4_f3d_lights;
extern Lights1 bitfs_dl__1_f3d_lights;
extern Lights1 bitfs_dl__2_f3d_lights;
extern Lights1 bitfs_dl__3_f3d_lights;
extern u8 bitfs_dl__auto_5_ci4[];
extern u8 bitfs_dl__auto_5_ci4_pal_rgba16[];
extern u8 bitfs_dl__auto_4_i8[];
extern u8 bitfs_dl__1_ci4[];
extern u8 bitfs_dl__1_ci4_pal_rgba16[];
extern u8 bitfs_dl__2_ci4[];
extern u8 bitfs_dl__2_ci4_pal_rgba16[];
extern u8 bitfs_dl__3_ci4[];
extern u8 bitfs_dl__3_ci4_pal_rgba16[];
extern Vtx bitfs_dl_bully_mesh_layer_1_vtx_cull[8];
extern Vtx bitfs_dl_bully_mesh_layer_1_vtx_0[18] __attribute__((section(".data")));
extern Gfx bitfs_dl_bully_mesh_layer_1_tri_0[];
extern Vtx bitfs_dl_bully_mesh_layer_1_vtx_1[57];
extern Gfx bitfs_dl_bully_mesh_layer_1_tri_1[];
extern Vtx bitfs_dl_bully_mesh_layer_1_vtx_2[26];
extern Gfx bitfs_dl_bully_mesh_layer_1_tri_2[];
extern Vtx bitfs_dl_bully_mesh_layer_1_vtx_3[10];
extern Gfx bitfs_dl_bully_mesh_layer_1_tri_3[];
extern Vtx bitfs_dl_bully_mesh_layer_1_vtx_4[12];
extern Gfx bitfs_dl_bully_mesh_layer_1_tri_4[];
extern Gfx mat_bitfs_dl__auto_5_f3d[];
extern Gfx mat_revert_bitfs_dl__auto_5_f3d[];
extern Gfx mat_bitfs_dl__auto_4_f3d[];
extern Gfx mat_revert_bitfs_dl__auto_4_f3d[];
extern Gfx mat_bitfs_dl__1_f3d[];
extern Gfx mat_revert_bitfs_dl__1_f3d[];
extern Gfx mat_bitfs_dl__2_f3d[];
extern Gfx mat_revert_bitfs_dl__2_f3d[];
extern Gfx mat_bitfs_dl__3_f3d[];
extern Gfx mat_revert_bitfs_dl__3_f3d[];
extern Gfx bitfs_dl_bully_mesh_layer_1[];
extern Gfx bitfs_dl_material_revert_render_settings[];
