extern const GeoLayout triarc_comb_geo[];
extern Lights1 triarc_comb__23_f3d_lights;
extern u8 triarc_comb__23_ci4[];
extern u8 triarc_comb__23_ci4_pal_rgba16[];
extern Vtx triarc_comb_waterfally_uv_003_mesh_layer_1_vtx_cull[8];
extern Vtx triarc_comb_waterfally_uv_003_mesh_layer_1_vtx_0[82];
extern Gfx triarc_comb_waterfally_uv_003_mesh_layer_1_tri_0[];
extern Gfx mat_triarc_comb__23_f3d[];
extern Gfx mat_revert_triarc_comb__23_f3d[];
extern Gfx triarc_comb_waterfally_uv_003_mesh_layer_1[];
extern Gfx triarc_comb_material_revert_render_settings[];
